# SPDX-FileCopyrightText: 2025 Lennart Dohmann <lennart.dohmann@gdata.de>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  nextcloud-container:
    image: nextcloud:32.0.0
    ports:
      - "8080:80"
    container_name: nextcloud-container
    hostname: nextcloud-container
    depends_on:
      - smtp
    restart: unless-stopped
    networks:
      nextcloud-network:
  smtp:
    image: rnwood/smtp4dev:latest
    container_name: smtp
    hostname: smtp
    restart: unless-stopped
    environment:
      ServerOptions__DisableIPv6: true
    ports:
      - "8081:80"
    networks:
      - nextcloud-network

  garaged:
    image: dxflrs/garage:v2.1.0
    container_name: garaged
    hostname: garaged
    restart: unless-stopped
    volumes:
      - ./garage.toml:/etc/garage.toml
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    networks: 
      - nextcloud-network

networks:
  nextcloud-network:
